-- AlterTable
ALTER TABLE `Room` ADD COLUMN `banLa` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `bep` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `dieuHoa` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `doXe` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `giaTien` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `giuong` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `hinhAnh` VARCHAR(191) NULL,
    ADD COLUMN `hoBoi` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `khach` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `maViTri` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `mayGiat` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `phongNgu` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `phongTam` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `tivi` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `wifi` BOOLEAN NOT NULL DEFAULT false;

-- AddForeignKey
ALTER TABLE `Room` ADD CONSTRAINT `Room_maViTri_fkey` FOREIGN KEY (`maViTri`) REFERENCES `Location`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
